=== cksharma/coding/workspace/FirstWebPr/WebContent/EmployeeList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.onmobile.com/EmployeeList" 
xmlns:onmobile="http://www.onmobile.com/EmployeeList"
elementFormDefault="qualified">

    <xsd:complexType name="Employee">
    	<xsd:sequence>
    		<xsd:element name="EmployeeId">
    			<xsd:simpleType>
    				<xsd:restriction base="xsd:int">
    					<xsd:minInclusive value="1"></xsd:minInclusive>
    					<xsd:maxInclusive value="100"></xsd:maxInclusive>
    				</xsd:restriction>
    			</xsd:simpleType>
    		</xsd:element>
    		<xsd:element name="name" type="xsd:string"></xsd:element>
    		<xsd:element name="designation" type="xsd:string"></xsd:element>
    		<xsd:element name="salary" type="xsd:double"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="EmployeeListType">
    	<xsd:sequence>
    		<xsd:element name="Employee" type="onmobile:Employee" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:element name = "EmployeeList" type = "onmobile:EmployeeListType"></xsd:element>
    

    <xsd:complexType name="Customer">
    	<xsd:sequence>
    		<xsd:element name="name" type="xsd:string"></xsd:element>
    		<xsd:element name="id" type="xsd:int"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:element name="CustomerList" type="onmobile:CustomerListType"></xsd:element>
    
    <xsd:complexType name="CustomerListType">
    	<xsd:sequence>
    		<xsd:element name="customer" type="onmobile:Customer" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
</xsd:schema>

<!-- if i do xsd:schema then have to do xmlns:xsd also-->
<!-- qualified means that I have to use tags from default name namespaces... -->
<!-- schema is predefined tag in w3.org/2001/XMLSchema -->

=== cksharma/coding/workspace/FirstWebPr/WebContent/emplist.xml
<?xml version="1.0" encoding="UTF-8"?>
<onmobile:EmployeeList xmlns:onmobile="http://www.onmobile.com/EmployeeList"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.onmobile.com/EmployeeList EmployeeList.xsd ">
	<onmobile:Employee>
		<onmobile:EmployeeId>2</onmobile:EmployeeId>
		<onmobile:name>Rajesh</onmobile:name>
		<onmobile:designation>Developer</onmobile:designation>
		<onmobile:salary>40000</onmobile:salary>
	</onmobile:Employee>

	<onmobile:Employee>
		<onmobile:EmployeeId>1</onmobile:EmployeeId>
		<onmobile:name>Arvind</onmobile:name>
		<onmobile:designation>Developer</onmobile:designation>
		<onmobile:salary>60000</onmobile:salary>
	</onmobile:Employee>

</onmobile:EmployeeList>
