=== cksharma/coding/workspace/FirstPrj/OrderListType.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.onmobile.com/OrderListType" 
xmlns:purchase="http://www.onmobile.com/OrderListType" 
elementFormDefault="qualified">
    

    <xsd:complexType name="Order">
    	<xsd:sequence>
    		<xsd:element name="orderId" type="xsd:int"></xsd:element>
    		<xsd:element name="itemId" type="xsd:int"></xsd:element>
    		<xsd:element name="qtyRequired" type="xsd:int"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="OrderList">
    	<xsd:sequence>
    		<xsd:element name="Order" type="purchase:Order" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:element name="OrderList" type="purchase:OrderList"></xsd:element>
</xsd:schema>

=== cksharma/coding/workspace/FirstPrj/Order.xml
<?xml version="1.0" encoding="UTF-8"?>
<purchase:OrderList xmlns:purchase="http://www.onmobile.com/OrderListType" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.onmobile.com/OrderListType OrderListType.xsd ">
  <purchase:Order>
    <purchase:orderId>1</purchase:orderId>
    <purchase:itemId>101</purchase:itemId>
    <purchase:qtyRequired>3</purchase:qtyRequired>
  </purchase:Order>
    <purchase:Order>
    <purchase:orderId>2</purchase:orderId>
    <purchase:itemId>102</purchase:itemId>
    <purchase:qtyRequired>2</purchase:qtyRequired>
  </purchase:Order>
</purchase:OrderList>
